# Generated by Django 2.1.3 on 2018-11-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_stockmodel_hunter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmodel',
            name='hunter',
        ),
    ]
