# Generated by Django 2.1.3 on 2018-11-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0004_remove_stockmodel_hunter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock/'),
        ),
    ]
